from typing import ContextManager, Protocol


class ReporterProtocol(Protocol):
    @property
    def report_all_methods(self) -> bool: ...

    @report_all_methods.setter
    def report_all_methods(self, value: bool) -> None: ...

    @property
    def is_current_stage_passed(self) -> bool: ...

    @is_current_stage_passed.setter
    def is_current_stage_passed(self, value: bool) -> None: ...

    def step(self, name: str, *args) -> ContextManager: ...
    def attach_text(self, *args) -> None: ...
    def __enter__(self, *args) -> None: ...
    def __exit__(self, *args) -> None: ...
    def step_decorator(self, *args, **kwargs) -> None: ...
    def static_step_decorator(self, *args, **kwargs) -> None: ...
